package compiler;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READLINE = 47;
  public static final int OSB = 9;
  public static final int MULT = 35;
  public static final int DOUBLE = 6;
  public static final int MINUSA = 29;
  public static final int SEMI = 4;
  public static final int PRIVATE = 19;
  public static final int CONTINUE = 26;
  public static final int T_DOUBLELITERAL = 65;
  public static final int INT = 5;
  public static final int LESS = 38;
  public static final int FOR = 24;
  public static final int MINUS = 34;
  public static final int DEFINE = 3;
  public static final int OCB = 17;
  public static final int NOT = 46;
  public static final int AND = 44;
  public static final int READINTEGER = 59;
  public static final int OR = 45;
  public static final int BOOL = 7;
  public static final int COMMA = 15;
  public static final int CLASS = 16;
  public static final int T_INTLITERAL = 64;
  public static final int DIV = 36;
  public static final int ORB = 12;
  public static final int NEWARRAY = 61;
  public static final int DEFINECHARS = 60;
  public static final int MOREEQ = 41;
  public static final int PLUS = 33;
  public static final int LESSEQ = 39;
  public static final int ASSIGN = 27;
  public static final int IF = 21;
  public static final int THIS = 32;
  public static final int ID = 62;
  public static final int DOT = 55;
  public static final int CSB = 10;
  public static final int EOF = 0;
  public static final int RETURN = 57;
  public static final int DTIO = 50;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int T_STRINGLITERAL = 63;
  public static final int PERCENT = 37;
  public static final int LINE = 53;
  public static final int NULL = 56;
  public static final int EQEQ = 42;
  public static final int BREAK = 25;
  public static final int VOID = 14;
  public static final int IMPORT = 2;
  public static final int CCB = 18;
  public static final int PLUSA = 28;
  public static final int BTIO = 52;
  public static final int DIVA = 31;
  public static final int ELSE = 22;
  public static final int FUNC = 54;
  public static final int ITOD = 49;
  public static final int ITOB = 51;
  public static final int WHILE = 23;
  public static final int CRB = 13;
  public static final int PUBLIC = 20;
  public static final int STRING = 8;
  public static final int OCSB = 11;
  public static final int T_BOOLEANLITERAL = 66;
  public static final int MULTA = 30;
  public static final int PRINT = 58;
  public static final int MORE = 40;
  public static final int NOTEQ = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPORT",
  "DEFINE",
  "SEMI",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "OSB",
  "CSB",
  "OCSB",
  "ORB",
  "CRB",
  "VOID",
  "COMMA",
  "CLASS",
  "OCB",
  "CCB",
  "PRIVATE",
  "PUBLIC",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "ASSIGN",
  "PLUSA",
  "MINUSA",
  "MULTA",
  "DIVA",
  "THIS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "PERCENT",
  "LESS",
  "LESSEQ",
  "MORE",
  "MOREEQ",
  "EQEQ",
  "NOTEQ",
  "AND",
  "OR",
  "NOT",
  "READLINE",
  "NEW",
  "ITOD",
  "DTIO",
  "ITOB",
  "BTIO",
  "LINE",
  "FUNC",
  "DOT",
  "NULL",
  "RETURN",
  "PRINT",
  "READINTEGER",
  "DEFINECHARS",
  "NEWARRAY",
  "ID",
  "T_STRINGLITERAL",
  "T_INTLITERAL",
  "T_DOUBLELITERAL",
  "T_BOOLEANLITERAL"
  };
}

